/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_29 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] sum1,
    output reg v,
    output reg z,
    output reg n
  );
  
  
  
  reg [15:0] sum;
  
  always @* begin
    
    case (alufn[0+0-:1])
      1'h0: begin
        sum = a + b;
        v = (((a[15+0-:1]) & (b[15+0-:1]) & (~sum[15+0-:1])) | ((~a[15+0-:1]) & (~b[15+0-:1]) & (sum[15+0-:1])));
      end
      1'h1: begin
        sum = a - b;
        v = (((a[15+0-:1]) & (~b[15+0-:1]) & (~sum[15+0-:1])) | ((~a[15+0-:1]) & (b[15+0-:1]) & (sum[15+0-:1])));
      end
      default: begin
        sum = a + b;
        v = (((a[15+0-:1]) & (b[15+0-:1]) & (~sum[15+0-:1])) | ((~a[15+0-:1]) & (~b[15+0-:1]) & (sum[15+0-:1])));
      end
    endcase
    sum1 = sum[0+15-:16];
    z = (~|sum);
    n = sum[15+0-:1];
  end
endmodule
