/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_20 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] alu,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  wire [16-1:0] M_add_sum1;
  wire [1-1:0] M_add_v;
  wire [1-1:0] M_add_z;
  wire [1-1:0] M_add_n;
  reg [6-1:0] M_add_alufn;
  reg [16-1:0] M_add_a;
  reg [16-1:0] M_add_b;
  adder_29 add (
    .alufn(M_add_alufn),
    .a(M_add_a),
    .b(M_add_b),
    .sum1(M_add_sum1),
    .v(M_add_v),
    .z(M_add_z),
    .n(M_add_n)
  );
  
  wire [16-1:0] M_comp_cmp1;
  reg [6-1:0] M_comp_alufn;
  reg [1-1:0] M_comp_v;
  reg [1-1:0] M_comp_z;
  reg [1-1:0] M_comp_n;
  compare_30 comp (
    .alufn(M_comp_alufn),
    .v(M_comp_v),
    .z(M_comp_z),
    .n(M_comp_n),
    .cmp1(M_comp_cmp1)
  );
  
  wire [16-1:0] M_boole_bool;
  reg [6-1:0] M_boole_alufn;
  reg [16-1:0] M_boole_a;
  reg [16-1:0] M_boole_b;
  boolean_31 boole (
    .alufn(M_boole_alufn),
    .a(M_boole_a),
    .b(M_boole_b),
    .bool(M_boole_bool)
  );
  
  wire [16-1:0] M_shift_s;
  reg [16-1:0] M_shift_a;
  reg [16-1:0] M_shift_b;
  reg [6-1:0] M_shift_alufn;
  shifter_32 shift (
    .a(M_shift_a),
    .b(M_shift_b),
    .alufn(M_shift_alufn),
    .s(M_shift_s)
  );
  
  always @* begin
    M_add_a = a;
    M_add_b = b;
    M_add_alufn = alufn;
    M_comp_v = M_add_v;
    M_comp_n = M_add_n;
    M_comp_z = M_add_z;
    M_comp_alufn = alufn;
    M_boole_a = a;
    M_boole_b = b;
    M_boole_alufn = alufn;
    M_shift_a = a;
    M_shift_b = b;
    M_shift_alufn = alufn;
    
    case (alufn[4+1-:2])
      2'h0: begin
        alu = M_add_sum1;
      end
      2'h1: begin
        alu = M_boole_bool;
      end
      2'h2: begin
        alu = M_shift_s;
      end
      2'h3: begin
        alu = M_comp_cmp1;
      end
      default: begin
        alu = 16'h0000;
      end
    endcase
    z = M_add_z;
    v = M_add_v;
    n = M_add_n;
  end
endmodule
