/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multiply_33 (
    input [7:0] a,
    input [7:0] b,
    output reg [15:0] mul
  );
  
  
  
  reg [7:0] p0;
  
  reg [7:0] p1;
  
  reg [7:0] p2;
  
  reg [7:0] p3;
  
  reg [7:0] p4;
  
  reg [7:0] p5;
  
  reg [7:0] p6;
  
  reg [7:0] p7;
  
  always @* begin
    p0[0+7-:8] = ({4'h8{a[0+0-:1]}}) & (b[0+7-:8]);
    p1[0+7-:8] = (({4'h8{a[1+0-:1]}}) & (b[0+7-:8])) << 1'h1;
    p2[0+7-:8] = (({4'h8{a[2+0-:1]}}) & (b[0+7-:8])) << 2'h2;
    p3[0+7-:8] = (({4'h8{a[3+0-:1]}}) & (b[0+7-:8])) << 2'h3;
    p4[0+7-:8] = (({4'h8{a[4+0-:1]}}) & (b[0+7-:8])) << 3'h4;
    p5[0+7-:8] = (({4'h8{a[5+0-:1]}}) & (b[0+7-:8])) << 3'h5;
    p6[0+7-:8] = (({4'h8{a[6+0-:1]}}) & (b[0+7-:8])) << 3'h6;
    p7[0+7-:8] = (({4'h8{a[7+0-:1]}}) & (b[0+7-:8])) << 3'h7;
    mul = p0 + p1 + p2 + p3 + p4 + p5 + p6 + p7;
  end
endmodule
